# Generated by Django 2.1.5 on 2019-02-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='longurl',
            name='code',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
